//
//  BookListInteractor.swift
//  jinybookassessment
//
//  Created by Manikandan Tamilselvan on 08/07/19.
//  Copyright (c) 2019 widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookListBusinessLogic
{
    func fetchBookDataBy(type: String, query: String)
}

protocol BookListDataStore
{
}

class BookListInteractor: BookListBusinessLogic, BookListDataStore
{
    var presenter: BookListPresentationLogic?
    var worker: BookListWorker?
    
    func fetchBookDataBy(type: String, query: String) {
        worker = BookListWorker()
        worker?.fetchBookList(type, query: query, callback: { (res) in
            self.presenter?.presentBookList(response: res)
        })
    }
}
