//
//  BookListWorker.swift
//  jinybookassessment
//
//  Created by Manikandan Tamilselvan on 08/07/19.
//  Copyright (c) 2019 widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BookListWorker
{
    func fetchBookList(_ type:String, query: String, callback:@escaping ([BookDetailsEntity])->()) {
        BookDetailRepo().fetchBookList(type, query: query) { (res) in
            callback(res)
        }
    }
}
