//
//  BookListPresenter.swift
//  jinybookassessment
//
//  Created by Manikandan Tamilselvan on 08/07/19.
//  Copyright (c) 2019 widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookListPresentationLogic
{
    func presentBookList(response:[BookDetailsEntity])
}

class BookListPresenter: BookListPresentationLogic
{
    weak var viewController: BookListDisplayLogic?

    func presentBookList(response: [BookDetailsEntity]) {
        if response.count > 0 {
            self.viewController?.showBookList(viewModel: response)
        }else {
            self.viewController?.showFailureData()
        }
    }
}
