//
//  HomeWorker.swift
//  jinybookassessment
//
//  Created by Manikandan Tamilselvan on 08/07/19.
//  Copyright (c) 2019 widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class HomeWorker
{
    // MARK: Get All Books
    
    func getAllBooksFromServer(callback: @escaping ([BookDetailsEntity]) -> ()) {
        
        let iBookRepo : BookListInterface = BookListRepo()
        
        iBookRepo.getAllBooks { (response, error) in
            DispatchQueue.main.async {
                if response.count > 0 {
                    callback(response)
                }else{
                    callback([])
                }
            }
        }
    }
}
