//
//  HomeInteractor.swift
//  jinybookassessment
//
//  Created by Manikandan Tamilselvan on 08/07/19.
//  Copyright (c) 2019 widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
    func fetchAllBook()
}

protocol HomeDataStore
{
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    
    // MARK: Do get book list
    
    func fetchAllBook() {
        
        worker = HomeWorker()
        worker?.getAllBooksFromServer(callback: { (res) in
            self.presenter?.presentBookListToUI(res: res)
        })
    }
}
