//
//  HomeRouter.swift
//  jinybookassessment
//
//  Created by Manikandan Tamilselvan on 08/07/19.
//  Copyright (c) 2019 widas. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
    func routerToBookListPage(type:String, query:String)
}

protocol HomeDataPassing
{
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    // MARK: Routing
    
    func routerToBookListPage(type:String, query:String)
    {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let bookListPage = storyboard.instantiateViewController(withIdentifier: "BookListViewController") as! BookListViewController
        bookListPage.type = type
        bookListPage.query = query
        self.navigateToBookList(source: viewController!, destination: bookListPage)
    }
    
    // MARK: Navigating
    
    func navigateToBookList(source: HomeViewController, destination: BookListViewController)
    {
        source.show(destination, sender: nil)
    }
}
